# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Hexo Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        - node-version: ${{ matrix.node-version }}
- run: hexo g
- run: git config --local user.email "kiwichang2017@gmail.com"
- run: git config --local user.name "charlie-moomoo的分身"
- run: git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
- run: git pull --rebase
    - run: npm install hexo-cli -g
    - run: hexo init blog
    - run: cd blog
    - run: hexo server
    - run: hexo new "Hello Hexo"
    - run: hexo generate
    - run: git add .
- run: git commit -m "apply blog"
- run: git push
